#pragma config(Sensor, dgtl7,  bump,           sensorTouch)
#pragma config(Motor,  port2,           rightside,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftside,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           hpsucker,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           hphammer,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           trashcancollect1, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           trashcancollect2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ballcollect2,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ballcollect1,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(int throttle, int wheel)
{
	if (abs(throttle) < 10) throttle = 0;
	if (abs(wheel) < 10) wheel = 0;

	if (abs(throttle) > 127) throttle = 127;
	if (abs(wheel) > 127) wheel = 127;

	motor[leftside] = throttle - wheel;
	motor[rightside] = throttle + wheel;

}
int have_can =0;
//5d suck 5u spit
void control(int trashin, int trashout, int ballstage1in, int ballstage1out, int ballstage2in, int ballstage2out, int hpin,
int hpout, int hpsuck)
{
	/*if(SensorValue[bump] == 1) //when trashcan is in
	{
		if(trashin) // trash in
		{
			motor[trashcancollect1] = -127; motor[trashcancollect2] = -127;
		}

		else if(trashout)
		{
			motor[trashcancollect1] = 127; motor[trashcancollect2] = 127;
		}

		else
		{
			motor[trashcancollect1] = 0; motor[trashcancollect2] = 0;
		}
	}

	if(SensorValue[bump] == 0) //when trash can is out
	{
		if(trashin) // trash in
		{
			motor[trashcancollect1] = -127; motor[trashcancollect2] = -127;
		}

		else if(trashout)
		{
			motor[trashcancollect1] = 127; motor[trashcancollect2] = 127;
		}

		else
		{
			motor[trashcancollect1] = -127; motor[trashcancollect2] = -127;
		}


	}
	*/
	if(have_can == 0)
	{
		if(SensorValue(bump) == 0) //can not in
		{
			if (trashin)
			{
				motor[trashcancollect1] = -127; motor[trashcancollect2] = -127;
			}

			else if (trashout)
			{
				motor[trashcancollect1] = 127; motor[trashcancollect2] = 127;
			}

			else
			{
				motor[trashcancollect1] = 0; motor[trashcancollect2] = 0;}
	   	}

	 else
	 {
	   have_can = 1;
	 }
	}

	else
	{ // Have can == True
		if(SensorValue(bump) == 0)
		{
			if (trashin)
			{
				motor[trashcancollect1] = -127; motor[trashcancollect2] = -127;
			}

			else if (trashout)
			{
				motor[trashcancollect1] = 127; motor[trashcancollect2] = 127; have_can =0;
			}

			else
			{
				motor[trashcancollect1] = -127; motor[trashcancollect2] = -127;
			}
		}
		else
		{//sensorvalue (Bump) == 0
			if(trashin)
			{
				motor[trashcancollect1] = 0; motor[trashcancollect2] = 0;
			}

			else if(trashout)
			{
				motor[trashcancollect1] = 127; motor[trashcancollect2] = 127; have_can =0;
			}
			else
			{
				motor[trashcancollect1] = 0; motor[trashcancollect2] = 0;
			}
		}
	}

	if(ballstage2out)
	{
		motor[ballcollect2] = 127;
	}

	else if(ballstage2in)
	{
		motor[ballcollect2] = -127;
	}

	else
	{
		motor[ballcollect2] = 0;
	}

	if(hpin)
	{
		motor[hphammer] = 127;
	}

	else if(hpout)
	{
		motor[hphammer] = -127;
	}

	else
	{
		motor[hphammer] = 0;
	}

	if(hpsuck)
	{
		motor[hpsucker] = -127;
	}

	else if(ballstage1in)
	{
		motor[hpsucker] = 127;
		motor[ballcollect1] = -127;
	}

	else if(ballstage1out)
	{
		motor[hpsucker] = 127;
		motor[ballcollect1] = 127;
	}
	else
	{
		motor[hpsucker] = 0;
		motor[ballcollect1] = 0;
	}

	if(motor[hpsucker] >127) motor[hpsucker] = 127;

}




task main()
{
	while(true)
	{
		drive(vexRT[Ch3], vexRT[Ch1]);
		control(vexRT[Btn7DXmtr2], vexRT[Btn7UXmtr2], vexRT[Btn6DXmtr2], vexRT[Btn6UXmtr2], vexRT[Btn5DXmtr2], vexRT[Btn5UXmtr2],vexRT[Btn8DXmtr2],
		vexRT[Btn8UXmtr2], vexRT[Btn8LXmtr2]);
	}					//trash in					//trashout				ballstage1in				ballstageiout				ballstage2in				ballstage2out
}